db_models/models.py
from config.database import db


class Product(db.Model):
    # Product model representing a product in the store
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    price = db.Column(db.Float, nullable=False)
    code = db.Column(db.String(50), unique=True, nullable=False)

    # Define a one-to-many relationship with CartItem model
    cart_items = db.relationship('CartItem', backref='product', lazy=True)

    def __repr__(self):
        return f'<Product {self.name}>'


class CartItem(db.Model):
    # CartItem model representing an item in a shopping cart
    id = db.Column(db.Integer, primary_key=True)
    quantity = db.Column(db.Integer, nullable=False)
    total_price = db.Column(db.Float, nullable=False)

    # Define foreign key relationships with Product and Cart models
    product_id = db.Column(db.Integer, db.ForeignKey(
        'product.id'), nullable=False)
    cart_id = db.Column(db.Integer, db.ForeignKey('cart.id'), nullable=False)

    def __repr__(self):
        return f'<CartItem {self.quantity} of {self.product.name}>'


class Cart(db.Model):
    # Cart model representing a user's shopping cart
    id = db.Column(db.Integer, primary_key=True)
    total_price = db.Column(db.Float, nullable=False)

    # Define a foreign key relationship to the User model
    user_id = db.Column(db.Integer, db.ForeignKey(
        'user.id'), unique=True, nullable=False)

    # Define a one-to-many relationship with CartItem model
    items = db.relationship('CartItem', backref='cart', lazy=True)

    def __repr__(self):
        return f'<Cart {self.id}>'


class User(db.Model):
    # User model representing a registered user
    id = db.Column(db.Integer, primary_key=True)
    user_name = db.Column(db.String(50), unique=True, nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=False)
    name = db.Column(db.String(255), nullable=False)

    # Define a one-to-one relationship with the Cart model
    cart = db.relationship('Cart', backref='user', uselist=False, lazy=True)

    def __repr__(self):
        return f'<User {self.id}>'

app.py
import os
from flask import Flask
from dotenv import load_dotenv
from config.assets import register_assets_for
from config.database import configure_local_database, db
from routes.routes import bp

# Load environment variables from .env file
load_dotenv()

# Create a Flask application instance with a secret
app = Flask(__name__)
app.secret_key = os.getenv('FLASK_SECRET_KEY')

# Configure the database
configure_local_database(app)

# Attach assets and static files
register_assets_for(app)

# Initialize the Flask application with the database
db.init_app(app)

# Register routes Blueprint
app.register_blueprint(bp)

# Entry point for running the Flask application
if __name__ == '__main__':
    with app.app_context():
        # Create tables in the database if they don't exist
        db.create_all()
    # Run the Flask application with debugging enabled on the specified port
    app.run(debug=True, port=os.getenv('FLASK_PORT'))

routes/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from sqlalchemy.exc import IntegrityError  # Import IntegrityError
from db_models.models import db, Product, CartItem, Cart, User

# Create a Blueprint instance for routes
bp = Blueprint('routes', __name__)

# Define your routes using the Blueprint


@bp.route('/')
def index():
    # Check if a user exists in the database
    user = User.query.first()
    if not user:
        # If no user is found, create a new user
        new_user = User(
            user_name='admin',
            email='user@admin.com',
            name='John Doe The Admin'
        )
        db.session.add(new_user)
        db.session.commit()
        # Reload the user object to ensure it's properly loaded
        user = User.query.first()

    # Retrieve all products from the database
    products = Product.query.all()
    # Render the index.html template with the products data
    return render_template('index.html', products=products, user=user)

# Route to add a product to the cart


@bp.route('/add_to_cart/<int:product_id>', methods=['POST'])
def add_to_cart(product_id):
    # Get the product object based on the product_id
    product = Product.query.get_or_404(product_id)
    # Retrieve the quantity of the product from the form data
    quantity = int(request.form['quantity'])

    # Get the current user
    user = User.query.first()  # TODO: Must retrieve the logged-in user

    # Check if the user has a cart, create one if not
    if not user.cart:
        cart = Cart(total_price=0.0, user=user)
        db.session.add(cart)
        db.session.commit()

    # Check if the product is already in the cart
    cart_item = CartItem.query.filter_by(
        product_id=product_id, cart_id=user.cart.id).first()
    if cart_item:
        # Update the quantity and total price of the existing cart item
        cart_item.quantity += quantity
        cart_item.total_price = cart_item.quantity * product.price
    else:
        # Calculate the total price for the new cart item
        total_price = product.price * quantity
        # Create a new cart item in the database
        cart_item = CartItem(product_id=product_id, quantity=quantity,
                             total_price=total_price, cart_id=user.cart.id)
        db.session.add(cart_item)

    # Commit the changes to the database
    db.session.commit()
    # Flash a success message
    flash('Product added to cart successfully!', 'success')
    # Redirect to the home page
    return redirect(url_for('routes.index'))

# Route to create a new product


@bp.route('/create_product', methods=['GET', 'POST'])
def create_product():
    # Check if the request method is POST and the user is 'admin'
    if request.method == 'POST' and User.query.filter_by(user_name='admin').first():
        # Retrieve product code, name, and price from the form data
        code = request.form['code']
        name = request.form['name']
        price = float(request.form['price'])

        # Create a new product in the database
        product = Product(name=name, price=price, code=code)
        db.session.add(product)

        try:
            db.session.commit()  # Try committing the changes
            # Flash a success message
            flash('Product created successfully!', 'success')
        except IntegrityError:
            db.session.rollback()  # Rollback the transaction
            # Flash a message indicating the code already exists
            flash('Product code already exists. Please choose a different code.', 'error')

        # Reloads as the proper way is having the function returning something
        return render_template('create_product.html')

    # Render the create_product.html template for GET requests or unauthorized POST requests
    return render_template('create_product.html')

# Route for the shopping cart


@bp.route('/cart')
def cart():
    # TODO: Retrieve the logged-in user's cart
    user_cart = User.query.first().cart

    if user_cart:
        # Retrieve all cart items associated with the user's cart
        cart_items = CartItem.query.filter_by(cart_id=user_cart.id).all()
        # Calculate the total cart price
        total_cart_price = sum(item.total_price for item in cart_items)

        # Ensure each CartItem object has a reference to its corresponding Product
        for item in cart_items:
            item.product = Product.query.get(item.product_id)

        # Render the cart.html template with the cart items and total cart price
        return render_template('cart.html', cart_items=cart_items, total_cart_price=total_cart_price)
    else:
        # Render the cart.html template with an empty cart message
        return render_template('cart.html', cart_items=[], total_cart_price=0)


# Return the Blueprint object for registration in app.py

def create_routes_blueprint():
    return bp

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>
    My Store
  </title>
  {% assets "bundle_css" %}
  <link rel="stylesheet" href="{{ ASSET_URL }}" />
  {% endassets %}
</head>

<body>
  <header class="app-header">
    <a class="logo-container" href="{{ url_for('routes.index') }}">My Store v1.0</a>
    <a href="{{ url_for('routes.cart') }}">Go to Cart</a>
    <a href="{{ url_for('routes.create_product') }}">Create New Product</a>
  </header>
  <main>
    {% block app_main_content %}{% endblock %}
  </main>
  <footer>
    <div class="container">
      <p class="footer-text">
        Developed by
        <a href="https://www.linkedin.com/in/renatolinsdigital" alt="Renato Lins Linkedin" target="_blank">Renato Lins</a>
      </p>
    </div>
  </footer>
  {% assets "bundle_js" %}
  <script src="{{ ASSET_URL }}"></script>
  {% endassets %}
</body>

</html>

templates/cart.html
{% extends 'base.html' %}

{% block app_main_content %}
<header class="app-hero">
  <h1>Your Shopping Cart</h1>
</header>
<div class="container page">
    {% if cart_items %}
        <ul class="container">
            {% for item in cart_items %}
              <li class="cart-entry">
                <p class="product-name">{{ item.product.name }}</p>
                <p>Quantity: {{ item.quantity }}</p>
                <p>Unit Price: ${{ item.product.price }}</p>
                <p>Total Price: ${{ item.total_price }}</p>
              </li>
            {% endfor %}
          </ul>

        <p class="cart-total">Total Cart Price: $ <span>{{ total_cart_price }}</span></p>

        <div class="cart-actions">
            <a class="button" href="{{ url_for('routes.index') }}">Keep shopping</a>
            <a class="button secondary" href="#">Checkout - WIP</a>
        </div>
    {% else %}
        <p>Your cart is empty.</p>
        <a class="button" href="{{ url_for('routes.index') }}">Start shopping</a>
    {% endif %}
</div>
{% endblock %}

templates/create_product.html
{% extends 'base.html' %}

{% block app_main_content %}
<header class="app-hero">
  <h1>Admin - Create Product</h1>
</header>
<div class="container page">
    <form class="form" action="{{ url_for('routes.create_product') }}" method="POST">
        <div class="form-entry">
            <label for="code">Product Code</label>
            <input type="text" id="code" name="code" required>
        </div>
        <div class="form-entry">
            <label for="name">Product Name</label>
            <input type="text" id="name" name="name" required>
        </div>
        <div class="form-entry">
            <label for="price">Price ($)</label>
            <input type="number" id="price" name="price" step="0.01" min="0" required>
        </div>
        <button class="button" type="submit">Create Product</button>
    </form>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endwith %}
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block app_main_content %}
<header class="app-hero">
    {% if user %}
    <h1>Welcome {{ user.name }}!</h1>
    {% else %}
    <h1>Welcome to My Store</h1>
    {% endif %}
</header>
<div class="container page">
    {% if products %}
    <ul class="grid-container">
        {% for product in products %}
        <li class="grid-item">
           <div class="product-image">No image</div>
            <p class="item-name">
              {{ product.name }}
            </p>
            <p class="author-creator">Author/Creator name</p>
            <p class="product-price">  $ {{ product.price }}</p>
            <form class="container" action="{{ url_for('routes.add_to_cart', product_id=product.id) }}" method="POST">
                <input class="removed" type="number" name="quantity" value="1" min="1">
                <button class="button stretched" type="submit">Add to Cart</button>
            </form>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No product has been registered yet.</p>
    {% endif %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}
</div>
{% endblock %}